- name: Demo on play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{URL}}

# in ansible variable will be access using {{}},
# ansible supports single and double quotes
#quotes are notmandatory if variable starts with value

- name: Demo on Task level variable
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{URL}}
  vars:
    URL: play.example.com
